// Import CSS styles
import './style.css';

// Export all composables
export * from './composables';

// Export all enums
export * from './enums';

// Export all helpers
export * from './helpers';

// Export all types and interfaces
export * from './types';

// Export all components
export * from './components';

// Re-export the commonly used public MapLibre GL types directly.
export type {
  AddProtocolAction,
  Alignment,
  AnimationOptions,
  AttributionControlOptions,
  CameraForBoundsOptions,
  CameraOptions,
  CanvasSourceSpecification,
  Config,
  CompleteMapOptions,
  ControlPosition,
  EaseToOptions,
  ErrorLike,
  Feature,
  FeatureFilter,
  FeatureIdentifier,
  FeatureState,
  FilterSpecification,
  FitBoundsOptions,
  FlyToOptions,
  FullscreenControlOptions,
  GeoJSONFeature,
  GeoJSONFeatureId,
  GeoJSONSourceSpecification,
  GeolocateControlOptions,
  GetResourceResponse,
  ICanonicalTileID,
  IControl,
  IMercatorCoordinate,
  ImageSourceSpecification,
  InterpolationType,
  JumpToOptions,
  LayerSpecification,
  LngLatBoundsLike,
  LngLatLike,
  MapContextEvent,
  MapDataEvent,
  MapEventType,
  MapGeoJSONFeature,
  MapLayerEventType,
  MapLayerMouseEvent,
  MapLayerTouchEvent,
  MapLibreEvent,
  MapLibreZoomEvent,
  MapOptions,
  MapProjectionEvent,
  MapSourceDataEvent,
  MapSourceDataType,
  MapStyleDataEvent,
  MapStyleImageMissingEvent,
  MapTerrainEvent,
  MarkerOptions,
  NavigationControlOptions,
  Padding,
  PaddingOptions,
  PointLike,
  PopupOptions,
  ProjectionSpecification,
  PropertyValueSpecification,
  QueryRenderedFeaturesOptions,
  QuerySourceFeatureOptions,
  RasterDEMSourceSpecification,
  RasterSourceSpecification,
  RequestParameters,
  ResolvedImage,
  ScaleControlOptions,
  SkySpecification,
  SourceExpression,
  SourceSpecification,
  SpriteOnDemandStyleImage,
  SpriteSpecification,
  StateSpecification,
  StyleImage,
  StyleImageData,
  StyleImageInterface,
  StyleImageMetadata,
  StyleOptions,
  StylePropertyExpression,
  StylePropertySpecification,
  StyleSetterOptions,
  StyleSpecification,
  StyleSwapOptions,
  TerrainSpecification,
  TransitionSpecification,
  UpdateImageOptions,
  VariableAnchorOffsetCollection,
  VectorSourceSpecification,
  VideoSourceSpecification,
} from 'maplibre-gl';

// Expose the full runtime surface under a namespace to avoid collisions with
// Vue components such as Marker and Popup while still making the exact upstream
// API available from this package.
export * as maplibregl from 'maplibre-gl';

// Re-export the upstream runtime surface directly where names do not conflict
// with this package. Marker and Popup stay available via aliases below.
export {
  AJAXError,
  AttributionControl,
  BoxZoomHandler,
  CanvasSource,
  Color,
  CooperativeGesturesHandler,
  DoubleClickZoomHandler,
  DragPanHandler,
  DragRotateHandler,
  EdgeInsets,
  ErrorEvent,
  Event,
  Evented,
  Formatted,
  FormattedSection,
  FullscreenControl,
  GeoJSONSource,
  GeolocateControl,
  GlobeControl,
  Hash,
  ImageSource,
  KeyboardHandler,
  LngLat,
  LngLatBounds,
  LogoControl,
  Map,
  MapMouseEvent,
  MapTouchEvent,
  MapWheelEvent,
  MercatorCoordinate,
  NavigationControl,
  Point,
  RasterDEMTileSource,
  RasterTileSource,
  ScaleControl,
  ScrollZoomHandler,
  Style,
  TerrainControl,
  TwoFingersTouchPitchHandler,
  TwoFingersTouchRotateHandler,
  TwoFingersTouchZoomHandler,
  TwoFingersTouchZoomRotateHandler,
  VectorTileSource,
  VideoSource,
  addProtocol,
  addSourceType,
  clearPrewarmedResources,
  config,
  createTileMesh,
  getMaxParallelImageRequests,
  getRTLTextPluginStatus,
  getVersion,
  getWorkerCount,
  getWorkerUrl,
  importScriptInWorkers,
  prewarm,
  removeProtocol,
  setMaxParallelImageRequests,
  setRTLTextPlugin,
  setWorkerCount,
  setWorkerUrl,
} from 'maplibre-gl';

export {
  Marker as MaplibreMarker,
  Popup as MaplibrePopup,
} from 'maplibre-gl';
